""" Paragraph Generator

This module is used to format strings of plant names into paragraphs.
The size of paragraphs and the number of paragraphs are passed into 
the paragraph_gen method. This method uses random from the numpy 
module to determine the number of sentences in each paragraph based 
on a pre-determined paragraph size.

"""

import random
from sentence_gen import sentence_gen

small = range(3, 6) #range of # of sentences in a small paragraph
medium = range(5, 16) #range of # of sentences in a medium paragraph
large = range(15, 26) #range of # of sentences in a large paragraph

def paragraph_gen(size, par_num):
  """ Generates a list of strings representing paragraphs
  
  Parameters:
    size (str): string from 'small', 'medium', or 'large' that 
      represents the size of the paragraphs to be generated by 
      determening the number of sentences in a paragraph.
    par_num (int): number of paragraphs to be generated
  
  Returns:
    list: a list of string representing paragraphs. Each element of 
      the list is a paragraph string.
  
  """
  
  size_list = ['small', 'medium', 'large'] #possible paragraph sizes
  sentence_num = 0
  paragraphs = [] #list of paragraphs
  
  if size in size_list: #checks if input is a valid size
    if size == 'small':
      for i in xrange(par_num):
        paragraph = "" #paragraph string
        sentence_num = random.choice(small) #chooses the number of sentences in a paragraph 
        paragraph = sentence_gen(size, sentence_num) #generates sentences 
        paragraphs.append(paragraph) #appends paragraph to the list
    if size == 'medium':
      for i in xrange(par_num):
        paragraph = ""
        sentence_num = random.choice(medium)
        paragraph = sentence_gen(size, sentence_num)
        paragraphs.append(paragraph)
    if size == 'large':
      for i in xrange(par_num):
        paragraph = ""
        sentence_num = random.choice(large)
        paragraph = sentence_gen(size, sentence_num)
        paragraphs.append(paragraph)
  else:
    print "not valid"
  return paragraphs
